/**************************************************************************************************
 * Examples in the C++ language (the 'Example-043' unit test).
 *
 * GitHub repository: http://github.com/davidcanino/C_plus_plus_examples
 *
 * Created by David Canino (canino.david@gmail.com), March 2017
 *
 * main.cpp - the source file, implementing the main function for the 'Example-043' unit test.
 **************************************************************************************************/
 
#include <iostream>
#include <fstream>
#include <chrono>
#include <random>
#include <cstdlib>
#include <string>
using namespace std;

/// The main function for the <i>Example-043</i> unit test.
int main(void)
{
	unsigned int seed1;
	string str;
	ofstream out;
	ifstream in;

	/* This is the 'Example-043' unit test, where the generation of several pseudo-random values through a 'Mersenne twister engine' is tested! */
    cout<<endl<<"\tThis is the 'Example-043' unit test in the C++ language."<<endl<<endl;
    cout.flush();
    
    /* TASK #1 - we construct a Mersenne twister engine, such that its seed is automatically generated from the system clock. */
	cout<<"\tConstructing a Mersenne twister engine 'm1', such that its seed is automatically generated from the current system clock ... ";
	seed1 = (unsigned int)std::chrono::system_clock::now().time_since_epoch().count();
	std::mt19937 m1 (seed1);
	cout<<"ok"<<endl;
	cout<<"\tThe current system clock is: "<<seed1<<"."<<endl;
	cout<<"\tThe minimum random value, generated by the Mersenne twister engine 'm1', is "<<m1.min()<<"."<<endl;
	cout<<"\tThe maximum random value, generated by the Mersenne twister engine 'm1', is "<<m1.max()<<"."<<endl;
	cout<<"\tGenerating a random value with the Mersenne twister engine 'm1': "<<m1()<<"."<<endl<<endl;
	cout.flush();
	
	/* TASK #2 - we read a (custom) string, inserted by the user, to be used as the new seed. */
	cout<<"\tPlease, insert a string to be used as the new seed: ";
	cout.flush();
	getline(cin,str);
	if(!cin)
	{
		cout<<endl<<"PLEASE, YOU MUST INSERT A VALID STRING TO BE USED AS THE NEW SEED!"<<endl<<endl<<"\tTHIS PROGRAM IS CLOSING ... "<<endl<<endl;
		cout.flush();
		return EXIT_FAILURE;
	}
	
	/* TASK #3 - if we arrive here, then we can construct a new Mersenne twister engine 'm2' and update the existing Mersenne twister engine 'm1' with the new seed! */
	cout<<endl<<"\tConstructing another Mersenne twister engine 'm2' (based on the new seed) ... ";
	cout.flush();
	std::seed_seq seed2 (str.begin(),str.end());
	std::mt19937 m2 (seed2);
	cout<<"ok"<<endl;
	cout<<"\tThe minimum random value, generated by the Mersenne twister engine 'm2', is "<<m2.min()<<"."<<endl;
	cout<<"\tThe maximum random value, generated by the Mersenne twister engine 'm2', is "<<m2.max()<<"."<<endl;
	cout<<"\tGenerating a random value with this Mersenne twister engine 'm2': "<<m2()<<"."<<endl;
	if(m1==m2) cout<<"\tThe internal states of the Mersenne twister engines 'm1' and 'm2' coincide (with respect to the operator '==')"<<endl;
	else cout<<"\tThe internal states of the Mersenne twister engines 'm1' and 'm2' do not coincide (with respect to the operator '==')"<<endl;
	if(m1!=m2) cout<<"\tThe internal states of the Mersenne twister engines 'm1' and 'm2' do not coincide (with respect to the operator '!=')"<<endl<<endl;
	else cout<<"\tThe internal states of the Mersenne twister engines 'm1' and 'm2' coincide (with respect to the operator '!=')"<<endl<<endl;
	cout<<"\tGenerating a random value with the Mersenne twister engine 'm1': "<<m1()<<"."<<endl;
	cout<<"\tUpdating the Mersenne twister engine 'm1' with the new seed (the same as the Mersenne twister engine 'm2') .. ";
	m1.seed(seed2);
	cout<<"ok"<<endl;
	if(m1==m2) cout<<"\tThe internal states of the Mersenne twister engines 'm1' and 'm2' coincide (with respect to the operator '==')"<<endl;
	else cout<<"\tThe internal states of the Mersenne twister engines 'm1' and 'm2' do not coincide (with respect to the operator '==')"<<endl;
	if(m1!=m2) cout<<"\tThe internal states of the Mersenne twister engines 'm1' and 'm2' do not coincide (with respect to the operator '!=')"<<endl<<endl;
	else cout<<"\tThe internal states of the Mersenne twister engines 'm1' and 'm2' coincide (with respect to the operator '!=')"<<endl<<endl;
	cout.flush();
	
	/* TASK #4 - generating several random values in order to align the Mersenne twister engines 'm1' and 'm2'. */
	cout<<"\tGenerating a random value with the Mersenne twister engine 'm1': "<<m1()<<"."<<endl;
	cout<<"\tGenerating another random value with the Mersenne twister engine 'm1': "<<m1()<<"."<<endl;
	cout<<"\tGenerating a random value with the Mersenne twister engine 'm2': "<<m2()<<"."<<endl;
	if(m1==m2) cout<<"\tThe internal states of the Mersenne twister engines 'm1' and 'm2' coincide (with respect to the operator '==')"<<endl;
	else cout<<"\tThe internal states of the Mersenne twister engines 'm1' and 'm2' do not coincide (with respect to the operator '==')"<<endl;
	if(m1!=m2) cout<<"\tThe internal states of the Mersenne twister engines 'm1' and 'm2' do not coincide (with respect to the operator '!=')"<<endl<<endl;
	else cout<<"\tThe internal states of the Mersenne twister engines 'm1' and 'm2' coincide (with respect to the operator '!=')"<<endl<<endl;
	cout.flush();
	
	/* TASK #5 - we validate the serialization operators! */
	cout<<"\tExporting the internal state of the Mersenne twister engine 'm1' on the 'm1.txt' file (with respect to the operator '<<') ... ";
	out.open("m1.txt");
	if(!out)
	{
		cout<<endl<<"\tCANNOT OPEN THE 'm1.txt' FILE."<<endl<<endl<<"\tTHIS PROGRAM IS CLOSING ... "<<endl<<endl;
		cout.flush();
		return EXIT_FAILURE;
	}
	
	/* The 'm1.txt' file is open! */
	out<<m1;
	out.close();
	cout<<"ok"<<endl<<"\tCreating another Mersenne twister engine 'm3' ... ";
	cout.flush();
	std::mt19937 m3;
	cout<<"ok"<<endl;
	cout.flush();
	if(m1==m3) cout<<"\tThe internal states of the Mersenne twister engines 'm1' and 'm3' coincide (with respect to the operator '==')"<<endl;
	else cout<<"\tThe internal states of the Mersenne twister engines 'm1' and 'm3' do not coincide (with respect to the operator '==')"<<endl;
	if(m1!=m3) cout<<"\tThe internal states of the Mersenne twister engines 'm1' and 'm3' do not coincide (with respect to the operator '!=')"<<endl<<endl;
	else cout<<"\tThe internal states of the Mersenne twister engines 'm1' and 'm3' coincide (with respect to the operator '!=')"<<endl<<endl;
	cout.flush();
	cout<<"\tSaving the internal state of the Mersenne twister engine 'm1' (from the 'm1.txt' file) into the Mersenne twister engine 'm3' (with respect to the operator '>>') ... ";
	in.open("m1.txt");
	if(!in)
	{
		cout<<endl<<"\tCANNOT OPEN THE 'm1.txt' FILE."<<endl<<endl<<"\tTHIS PROGRAM IS CLOSING ... "<<endl<<endl;
		cout.flush();
		return EXIT_FAILURE;
	}
	
	/* Saving everything from the 'm1.txt' file into the Mersenne twister engine 'm3'. */
	in>>m3;
	in.close();
	cout<<"ok"<<endl;
	if(m1==m3) cout<<"\tThe internal states of the Mersenne twister engines 'm1' and 'm3' coincide (with respect to the operator '==')"<<endl;
	else cout<<"\tThe internal states of the Mersenne twister engines 'm1' and 'm3' do not coincide (with respect to the operator '==')"<<endl;
	if(m1!=m3) cout<<"\tThe internal states of the Mersenne twister engines 'm1' and 'm3' do not coincide (with respect to the operator '!=')"<<endl<<endl;
	else cout<<"\tThe internal states of the Mersenne twister engines 'm1' and 'm3' coincide (with respect to the operator '!=')"<<endl<<endl;
	cout.flush();
	return EXIT_SUCCESS;
}
