/**********************************************************************************************
 * Examples in the C++ language (the test 'Example-047')
 *
 * GitHub repository: http://github.com/davidcanino/C_plus_plus_examples
 *
 * Created by David Canino (canino.david@gmail.com), January 2017
 *
 * main.cpp - the source file, implementing the main function for the test 'Example-047'.
 **********************************************************************************************/
 
#include <iostream>
#include <fstream>
#include <chrono>
#include <random>
#include <cstdlib>
#include <string>
using namespace std;

/// The custom alias for modeling a specific <i>Indepent bits</i> generator engine.
typedef std::independent_bits_engine<std::mt19937,64,std::uint_fast64_t> ind_generator;

/// The main function for the <i>Example-047</i> unit test.
int main(void)
{
	unsigned int seed1;
	string str;
	ofstream out;
	ifstream in;

	/* First, we construct a generator, such that its seed is automatically generated from the system clock. */
	cout<<endl<<"\tThis is the example 'Example-047' in the C++ language"<<endl<<endl;
    cout.flush();
    cout<<"\tConstructing an Independent bits generator engine 'i1', such that its seed is automatically generated from the system clock ... ";
    seed1 = (unsigned int)std::chrono::system_clock::now().time_since_epoch().count();
    ind_generator i1(seed1);
    cout<<"ok"<<endl;
	cout<<"\tSystem clock: "<<seed1<<endl;
	cout<<"\tThe minimum random value, generated by the generator 'i1', is: "<<i1.min()<<endl;
	cout<<"\tThe maximum random value, generated by the generator 'i1', is: "<<i1.max()<<endl;
	cout<<"\tGenerating a random value with the generator 'i1': "<<i1()<<endl<<endl;
	cout.flush();
	
	/* Now, we read a (custom) string, inserted by the user, to be used as the new seed. */
	cout<<"\tPlease, insert a string to be used as the new seed: ";
	cout.flush();
	getline(cin,str);
	if(!cin)
	{
		cout<<endl<<"PLEASE, INSERT A VALID STRING TO BE USED AS THE NEW SEED. THIS PROGRAM IS CLOSING ... "<<endl<<endl;
		cout.flush();
		return EXIT_FAILURE;
	}
	
	/* If we arrive here, then we can construct a new generator 'i2' and update the existing generator 'i1' with the new seed! */
	cout<<endl<<"\tConstructing another Independent bits generator engine 'i2', based on the new seed ... ";
	cout.flush();
	std::seed_seq seed2 (str.begin(),str.end());
	ind_generator i2 (seed2);
	cout<<"ok"<<endl;
	cout<<"\tThe minimum random value, generated by the generator 'i2', is: "<<i2.min()<<endl;
	cout<<"\tThe maximum random value, generated by the generator 'i2', is: "<<i2.max()<<endl;
	cout<<"\tGenerating a random value with this generator 'i2': "<<i2()<<endl<<endl;
	if(i1==i2) cout<<"\tThe generators 'i1' and 'i2' coincide (wrt the operator '==')"<<endl;
	else cout<<"\tThe generators 'i1' and 'i2' do not coincide (wrt the operator '==')"<<endl;
	if(i1!=i2) cout<<"\tThe generators 'i1' and 'i2' do not coincide (wrt the operator '!=')"<<endl<<endl;
	else cout<<"\tThe generators 'i1' and 'i2' coincide (wrt the operator '!=')"<<endl<<endl;
	cout.flush();
	cout<<"\tGenerating a random value with the generator 'i1': "<<i1()<<endl;
	cout<<"\tUpdating the generator 'i1' with the new seed (the same as the generator 'i2') .. ";
	i1.seed(seed2);
	cout<<"ok"<<endl;
    if(i1==i2) cout<<"\tThe generators 'i1' and 'i2' coincide (wrt the operator '==')"<<endl;
	else cout<<"\tThe generators 'i1' and 'i2' do not coincide (wrt the operator '==')"<<endl;
	if(i1!=i2) cout<<"\tThe generators 'i1' and 'i2' do not coincide (wrt the operator '!=')"<<endl<<endl;
	else cout<<"\tThe generators 'i1' and 'i2' coincide (wrt the operator '!=')"<<endl<<endl;
	cout.flush();
	cout<<"\tGenerating a random value with the generator 'i1': "<<i1()<<endl;
	cout.flush();
	cout<<"\tGenerating another random value with the generator 'i1': "<<i1()<<endl;
	cout.flush();
	cout<<"\tGenerating a random value with the generator 'i2': "<<i2()<<endl;
	cout.flush();
	if(i1==i2) cout<<"\tThe generators 'i1' and 'i2' coincide (wrt the operator '==')"<<endl;
	else cout<<"\tThe generators 'i1' and 'i2' do not coincide (wrt the operator '==')"<<endl;
	if(i1!=i2) cout<<"\tThe generators 'i1' and 'i2' do not coincide (wrt the operator '!=')"<<endl<<endl;
	else cout<<"\tThe generators 'i1' and 'i2' coincide (wrt the operator '!=')"<<endl<<endl;
	cout.flush();
	
	/* Finally, we validate the serialization operators! */
	cout<<"\tExporting the internal state of the generator 'i1' on the 'i1.txt' file (wrt the operator '<<') ... ";
	out.open("i1.txt");
	if(!out)
	{
		cout<<endl<<"\tCANNOT OPEN THE 'i1.txt' FILE. THIS PROGRAM IS CLOSING ... "<<endl<<endl;
		cout.flush();
		return EXIT_FAILURE;
	}
	
	/* The 'i1.txt' file is open! */
	out<<i1;
	out.close();
	cout<<"ok"<<endl<<endl<<"\tCreating another generator 'i3' ... ";
	cout.flush();
	ind_generator i3;
	cout<<"ok"<<endl;
	cout.flush();
	if(i1==i3) cout<<"\tThe generators 'i1' and 'i3' coincide (wrt the operator '==')"<<endl;
	else cout<<"\tThe generators 'i1' and 'i3' do not coincide (wrt the operator '==')"<<endl;
	if(i1!=i3) cout<<"\tThe generators 'i1' and 'i3' do not coincide (wrt the operator '!=')"<<endl<<endl;
	else cout<<"\tThe generators 'i1' and 'i3' coincide (wrt the operator '!=')"<<endl<<endl;
	cout<<"\tSaving the internal state of the generator 'i1' (from the 'i1.txt' file) into the generator 'i3' (wrt the operator '>>') ... ";
    in.open("i1.txt");
	if(!in)
	{
		cout<<endl<<"\tCANNOT OPEN THE 'i1.txt' FILE. THIS PROGRAM IS CLOSING ... "<<endl<<endl;
		cout.flush();
		return EXIT_FAILURE;
	}
	
	/* Saving everything from the 'i1.txt' file into the generator 'i3'. */
	in>>i3;
	in.close();
	cout<<"ok"<<endl;
	cout.flush();
	if(i1==i3) cout<<"\tThe generators 'i1' and 'i3' coincide (wrt the operator '==')"<<endl;
	else cout<<"\tThe generators 'i1' and 'i3' do not coincide (wrt the operator '==')"<<endl;
	if(i1!=i3) cout<<"\tThe generators 'i1' and 'i3' do not coincide (wrt the operator '!=')"<<endl<<endl;
	else cout<<"\tThe generators 'i1' and 'i3' coincide (wrt the operator '!=')"<<endl<<endl;
	return EXIT_SUCCESS;    
}
