/**********************************************************************************************
 * Examples in the C++ language (the test 'Example-046')
 *
 * GitHub repository: http://github.com/davidcanino/C_plus_plus_examples
 *
 * Created by David Canino (canino.david@gmail.com), January 2017
 *
 * main.cpp - the source file, implementing the main function for the test 'Example-046'.
 **********************************************************************************************/
 
#include <iostream>
#include <fstream>
#include <chrono>
#include <random>
#include <cstdlib>
#include <string>
using namespace std;

/// The main function for the <i>Example-046</i> unit test.
int main(void)
{
	unsigned int seed1;
	string str;
	ofstream out;
	ifstream in;

	/* First, we construct a generator, such that its seed is automatically generated from the system clock. */
	cout<<endl<<"\tThis is the example 'Example-046' in the C++ language"<<endl<<endl;
    cout.flush();
    cout<<"\tConstructing a Discard-block generator engine 'r1', such that its seed is automatically generated from the system clock ... ";
    seed1 = (unsigned int)std::chrono::system_clock::now().time_since_epoch().count();
    std::ranlux24 r1(seed1);
    cout<<"ok"<<endl;
	cout<<"\tSystem clock: "<<seed1<<endl;
	cout<<"\tThe minimum random value, generated by the generator 'r1', is: "<<r1.min()<<endl;
	cout<<"\tThe maximum random value, generated by the generator 'r1', is: "<<r1.max()<<endl;
	cout<<"\tGenerating a random value with the generator 'r1': "<<r1()<<endl<<endl;
	cout.flush();
	
	/* Now, we read a (custom) string, inserted by the user, to be used as the new seed. */
	cout<<"\tPlease, insert a string to be used as the new seed: ";
	cout.flush();
	getline(cin,str);
	if(!cin)
	{
		cout<<endl<<"PLEASE, INSERT A VALID STRING TO BE USED AS THE NEW SEED. THIS PROGRAM IS CLOSING ... "<<endl<<endl;
		cout.flush();
		return EXIT_FAILURE;
	}
	
	/* If we arrive here, then we can construct a new generator 'r2' and update the existing generator 'r1' with the new seed! */
	cout<<endl<<"\tConstructing another Discard-block generator engine 'r2', based on the new seed ... ";
	cout.flush();
	std::seed_seq seed2 (str.begin(),str.end());
	std::ranlux24 r2 (seed2);
	cout<<"ok"<<endl;
	cout<<"\tThe minimum random value, generated by the generator 'r2', is: "<<r2.min()<<endl;
	cout<<"\tThe maximum random value, generated by the generator 'r2', is: "<<r2.max()<<endl;
	cout<<"\tGenerating a random value with this generator 'r2': "<<r2()<<endl<<endl;
	if(r1==r2) cout<<"\tThe generators 'r1' and 'r2' coincide (wrt the operator '==')"<<endl;
	else cout<<"\tThe generators 'r1' and 'r2' do not coincide (wrt the operator '==')"<<endl;
	if(r1!=r2) cout<<"\tThe generators 'r1' and 'r2' do not coincide (wrt the operator '!=')"<<endl<<endl;
	else cout<<"\tThe generators 'r1' and 'r2' coincide (wrt the operator '!=')"<<endl<<endl;
	cout.flush();
	cout<<"\tGenerating a random value with the generator 'r1': "<<r1()<<endl;
	cout<<"\tUpdating the generator 'r1' with the new seed (the same as the generator 'r2') .. ";
	r1.seed(seed2);
	cout<<"ok"<<endl;
    if(r1==r2) cout<<"\tThe generators 'r1' and 'r2' coincide (wrt the operator '==')"<<endl;
	else cout<<"\tThe generators 'r1' and 'r2' do not coincide (wrt the operator '==')"<<endl;
	if(r1!=r2) cout<<"\tThe generators 'r1' and 'r2' do not coincide (wrt the operator '!=')"<<endl<<endl;
	else cout<<"\tThe generators 'r1' and 'r2' coincide (wrt the operator '!=')"<<endl<<endl;
	cout.flush();
	cout<<"\tGenerating a random value with the generator 'r1': "<<r1()<<endl;
	cout.flush();
	cout<<"\tGenerating another random value with the generator 'r1': "<<r1()<<endl;
	cout.flush();
	cout<<"\tGenerating a random value with the generator 'r2': "<<r2()<<endl;
	cout.flush();
	if(r1==r2) cout<<"\tThe generators 'r1' and 'r2' coincide (wrt the operator '==')"<<endl;
	else cout<<"\tThe generators 'r1' and 'r2' do not coincide (wrt the operator '==')"<<endl;
	if(r1!=r2) cout<<"\tThe generators 'r1' and 'r2' do not coincide (wrt the operator '!=')"<<endl<<endl;
	else cout<<"\tThe generators 'r1' and 'r2' coincide (wrt the operator '!=')"<<endl<<endl;
	cout.flush();
	
	/* Finally, we validate the serialization operators! */
	cout<<"\tExporting the internal state of the generator 'r1' on the 'r1.txt' file (wrt the operator '<<') ... ";
	out.open("r1.txt");
	if(!out)
	{
		cout<<endl<<"\tCANNOT OPEN THE 'r1.txt' FILE. THIS PROGRAM IS CLOSING ... "<<endl<<endl;
		cout.flush();
		return EXIT_FAILURE;
	}
	
	/* The 'r1.txt' file is open! */
	out<<r1;
	out.close();
	cout<<"ok"<<endl<<endl<<"\tCreating another generator 'r3' ... ";
	cout.flush();
	std::ranlux24 r3;
	cout<<"ok"<<endl;
	cout.flush();
	if(r1==r3) cout<<"\tThe generators 'r1' and 'r3' coincide (wrt the operator '==')"<<endl;
	else cout<<"\tThe generators 'r1' and 'r3' do not coincide (wrt the operator '==')"<<endl;
	if(r1!=r3) cout<<"\tThe generators 'r1' and 'r3' do not coincide (wrt the operator '!=')"<<endl<<endl;
	else cout<<"\tThe generators 'r1' and 'r3' coincide (wrt the operator '!=')"<<endl<<endl;
	cout<<"\tSaving the internal state of the generator 'r1' (from the 'r1.txt' file) into the generator 'r3' (wrt the operator '>>') ... ";
    in.open("r1.txt");
	if(!in)
	{
		cout<<endl<<"\tCANNOT OPEN THE 'r1.txt' FILE. THIS PROGRAM IS CLOSING ... "<<endl<<endl;
		cout.flush();
		return EXIT_FAILURE;
	}
	
	/* Saving everything from the 'r1.txt' file into the generator 'r3'. */
	in>>r3;
	in.close();
	cout<<"ok"<<endl;
	cout.flush();
	if(r1==r3) cout<<"\tThe generators 'r1' and 'r3' coincide (wrt the operator '==')"<<endl;
	else cout<<"\tThe generators 'r1' and 'r3' do not coincide (wrt the operator '==')"<<endl;
	if(r1!=r3) cout<<"\tThe generators 'r1' and 'r3' do not coincide (wrt the operator '!=')"<<endl<<endl;
	else cout<<"\tThe generators 'r1' and 'r3' coincide (wrt the operator '!=')"<<endl<<endl;
    return EXIT_SUCCESS;
}
