/**************************************************************************************************
 * Examples in the C++ language (the 'Example-046' Test).
 *
 * GitHub repository: http://github.com/davidcanino/C_plus_plus_examples
 *
 * Created by David Canino (canino.david@gmail.com), April 2017
 *
 * main.cpp - the source file, implementing the main function for the 'Example-046' Test.
 **************************************************************************************************/
 
#include <iostream>
#include <fstream>
#include <chrono>
#include <random>
#include <cstdlib>
#include <string>
using namespace std;

/// The main function for the <i>'Example-046'</i> Test.
int main(void)
{
	unsigned int seed1;
	string str;
	ofstream out;
	ifstream in;
	
	/* This is the 'Example-046' Test, where the generation of several pseudo-random values through a 'Discard block engine' is tested! */
    cout<<endl<<"\tThis is the 'Example-046' Test in the C++ language."<<endl<<endl;
    cout.flush();
    
    /* TASK #1 - we construct a Discard block engine, such that its seed is automatically generated from the system clock. */
	cout<<"\tConstructing a Discard block engine 'd1', such that its seed is automatically generated from the current system clock ... ";
	seed1 = (unsigned int)std::chrono::system_clock::now().time_since_epoch().count();
	std::ranlux24 d1(seed1);
	cout<<"ok"<<endl;
	cout<<"\tThe current system clock is "<<seed1<<"."<<endl;
	cout<<"\tThe minimum random value, generated by the Discard block engine 'd1', is "<<d1.min()<<"."<<endl;
	cout<<"\tThe maximum random value, generated by the Discard block engine 'd1', is "<<d1.max()<<"."<<endl;
	cout<<"\tGenerating a random value with the Discard block engine 'd1': "<<d1()<<"."<<endl<<endl;
	cout.flush();
	
	/* TASK #2 - we read a (custom) string, inserted by the user, to be used as the new seed. */
	cout<<"\tPlease, insert a string to be used as the new seed: ";
	cout.flush();
	getline(cin,str);
	if(!cin)
	{
		cout<<endl<<"PLEASE, YOU MUST INSERT A VALID STRING TO BE USED AS THE NEW SEED!"<<endl<<endl<<"\tTHIS PROGRAM IS CLOSING ... "<<endl<<endl;
		cout.flush();
		return EXIT_FAILURE;
	}
	
	/* TASK #3 - if we arrive here, then we can construct a new Discard block engine 'd2' and update the existing Discard block engine 'd1' with the new seed! */
	cout<<endl<<"\tConstructing another Discard block engine 'd2' (based on the new seed) ... ";
	cout.flush();
	std::seed_seq seed2 (str.begin(),str.end());
	std::ranlux24 d2 (seed2);
	cout<<"ok"<<endl;
	cout<<"\tThe minimum random value, generated by the Discard block engine 'd2', is "<<d2.min()<<"."<<endl;
	cout<<"\tThe maximum random value, generated by the Discard block engine 'd2', is "<<d2.max()<<"."<<endl;
	cout<<"\tGenerating a random value with this Discard block engine 'd2': "<<d2()<<"."<<endl;
	if(d1==d2) cout<<"\tThe internal states of the Discard block engines 'd1' and 'd2' coincide (with respect to the operator '==')"<<endl;
	else cout<<"\tThe internal states of the Discard block engines 'd1' and 'd2' do not coincide (with respect to the operator '==')"<<endl;
	if(d1!=d2) cout<<"\tThe internal states of the Discard block engines 'd1' and 'd2' do not coincide (with respect to the operator '!=')"<<endl<<endl;
	else cout<<"\tThe internal states of the Discard block engines 'd1' and 'd2' coincide (with respect to the operator '!=')"<<endl<<endl;
	cout<<"\tGenerating a random value with the Discard block engine 'd1': "<<d1()<<"."<<endl;
	cout<<"\tUpdating the Discard block engine 'd1' with the new seed (the same as the Discard block engine 'd2') .. ";
	d1.seed(seed2);
	cout<<"ok"<<endl;
	if(d1==d2) cout<<"\tThe internal states of the Discard block engines 'd1' and 'd2' coincide (with respect to the operator '==')"<<endl;
	else cout<<"\tThe internal states of the Discard block engines 'd1' and 'd2' do not coincide (with respect to the operator '==')"<<endl;
	if(d1!=d2) cout<<"\tThe internal states of the Discard block engines 'd1' and 'd2' do not coincide (with respect to the operator '!=')"<<endl<<endl;
	else cout<<"\tThe internal states of the Discard block engines 'd1' and 'd2' coincide (with respect to the operator '!=')"<<endl<<endl;
	cout.flush();
    
    /* TASK #4 - generating several random values in order to align the Discard block engines 'd1' and 'd2'. */
	cout<<"\tGenerating a random value with the Discard block engine 'd1': "<<d1()<<"."<<endl;
	cout<<"\tGenerating another random value with the Discard block engine 'd1': "<<d1()<<"."<<endl;
	cout<<"\tGenerating a random value with the Discard block engine 'd2': "<<d2()<<"."<<endl;
	if(d1==d2) cout<<"\tThe internal states of the Discard block engines 'd1' and 'd2' coincide (with respect to the operator '==')"<<endl;
	else cout<<"\tThe internal states of the Discard block engines 'd1' and 'd2' do not coincide (with respect to the operator '==')"<<endl;
	if(d1!=d2) cout<<"\tThe internal states of the Discard block engines 'd1' and 'd2' do not coincide (with respect to the operator '!=')"<<endl<<endl;
	else cout<<"\tThe internal states of the Discard block engines 'd1' and 'd2' coincide (with respect to the operator '!=')"<<endl<<endl;
	cout.flush();
	
	/* TASK #5 - we validate the serialization operators! */
	cout<<"\tExporting the internal state of the Discard block engine 'd1' on the 'd1.txt' file (with respect to the operator '<<') ... ";
	out.open("d1.txt");
	if(!out)
	{
		cout<<endl<<"\tCANNOT OPEN THE 'd1.txt' FILE."<<endl<<endl<<"\tTHIS PROGRAM IS CLOSING ... "<<endl<<endl;
		cout.flush();
		return EXIT_FAILURE;
	}
	
	/* The 'd1.txt' file is open! */
	out<<d1;
	out.close();
	cout<<"ok"<<endl<<"\tCreating another Discard block engine 'd3' ... ";
	cout.flush();
	std::ranlux24 d3;
	cout<<"ok"<<endl;
	cout.flush();
	if(d1==d3) cout<<"\tThe internal states of the Discard block engines 'd1' and 'd3' coincide (with respect to the operator '==')"<<endl;
	else cout<<"\tThe internal states of the Discard block engines 'd1' and 'd3' do not coincide (with respect to the operator '==')"<<endl;
	if(d1!=d3) cout<<"\tThe internal states of the Discard block engines 'd1' and 'd3' do not coincide (with respect to the operator '!=')"<<endl<<endl;
	else cout<<"\tThe internal states of the Discard block engines 'd1' and 'd3' coincide (with respect to the operator '!=')"<<endl<<endl;
	cout.flush();
	cout<<"\tSaving the internal state of the Discard block engine 'd1' (from the 'd1.txt' file) into the Discard block engine 'd3' (with respect to the operator '>>') ... ";
	in.open("d1.txt");
	if(!in)
	{
		cout<<endl<<"\tCANNOT OPEN THE 'd1.txt' FILE."<<endl<<endl<<"\tTHIS PROGRAM IS CLOSING ... "<<endl<<endl;
		cout.flush();
		return EXIT_FAILURE;
	}
	
	/* Saving everything from the 'd1.txt' file into the Discard block engine 'd3'. */
	in>>d3;
	in.close();
	cout<<"ok"<<endl;
	if(d1==d3) cout<<"\tThe internal states of the Discard block engines 'd1' and 'd3' coincide (with respect to the operator '==')"<<endl;
	else cout<<"\tThe internal states of the Discard block engines 'd1' and 'd3' do not coincide (with respect to the operator '==')"<<endl;
	if(d1!=d3) cout<<"\tThe internal states of the Discard block engines 'd1' and 'd3' do not coincide (with respect to the operator '!=')"<<endl<<endl;
	else cout<<"\tThe internal states of the Discard block engines 'd1' and 'd3' coincide (with respect to the operator '!=')"<<endl<<endl;
	cout.flush();
	return EXIT_SUCCESS;
}
